# Related sites, rendered by {{< links >}}.

[[link]]
name = "Enlightenment Epplets"
url = "http://www.sanity.uklinux.net/epplets.html"

[[link]]
name = "Enlightenment themes at Freshmeat (transferred from themes.org)"
url = "http://themes.freshmeat.net/browse/60/"

[[link]]
name = "Rob's Enlightenment Page"
url = "http://cmdrtaco.net/linux/e.shtml"
