# Related sites, rendered by {{< links >}}.

[[link]]
name = "Largo's Window Maker Page"
url = "http://largo.windowmaker.org/"

[[link]]
name = "Window Maker Themes page at Freshmeat (transferred from themes.org)"
url = "http://themes.freshmeat.net/browse/918/"

[[link]]
name = "DHTML Window Maker Simulation"
url = "http://home.austin.rr.com/spork/WindowMaker/"

[[link]]
name = "Window Maker info"
url = "http://www.gwi.net/~aljordan/Windowmaker/"
