# Related sites, rendered by {{< links >}}.

[[link]]
name = "KDE-Look.org"
url = "http://www.kdelook.org/"

[[link]]
name = "KDE-Apps.org"
url = "http://www.kde-apps.org"

[[link]]
name = "KDE themes at Freshmeat"
url = "http://themes.freshmeat.net/browse/57/"
