#!/usr/bin/env python3
"""Check every link in public/: internal ones against the built tree, external ones over the network.
Writes a Markdown report to docs/links.md."""
import os, re, sys, ssl, socket, datetime, urllib.request, urllib.error, urllib.parse
from concurrent.futures import ThreadPoolExecutor
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
SITE_HOSTS = ("xwinman.org", "xteddy.org", "plig.net")
UA = "Mozilla/5.0 (X11; Linux x86_64) xwinman-linkcheck/1.0"
TIMEOUT = 20


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.out = []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        for k in ("href", "src"):
            if a.get(k):
                self.out.append(a[k])


def collect():
    """{url: [pages]} for every link, keyed by absolute URL or site-relative path."""
    found = {}
    for dp, _, files in os.walk(PUBLIC):
        for f in files:
            if not f.endswith(".html"):
                continue
            page = os.path.relpath(os.path.join(dp, f), PUBLIC)
            p = Links()
            with open(os.path.join(dp, f), "rb") as fh:
                p.feed(fh.read().decode("utf-8", "replace"))
            for href in p.out:
                href = href.split("#", 1)[0]
                if not href or href.startswith(("mailto:", "javascript:")):
                    continue
                if "://" in href:
                    key = href
                else:
                    key = os.path.normpath(os.path.join(os.path.dirname(page), href)).lstrip("./")
                    if href.endswith("/") or key == "":
                        key = (key + "/index.html").lstrip("/")
                found.setdefault(key, set()).add(page)
    return found


def probe(url):
    """('ok'|'redirect'|'dead', detail) for one external URL."""
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    if url.startswith("ftp://"):
        u = urllib.parse.urlsplit(url)
        try:
            with socket.create_connection((u.hostname, 21), timeout=TIMEOUT) as s:
                banner = s.recv(200).decode("latin-1", "replace").strip()
            return ("ok", "ftp banner: " + banner[:60])  # can't verify the path without logging in
        except OSError as e:
            return ("dead", str(e))
    for method in ("HEAD", "GET"):
        req = urllib.request.Request(url, method=method, headers={"User-Agent": UA})
        try:
            with urllib.request.urlopen(req, timeout=TIMEOUT, context=ctx) as r:
                final = r.geturl()
                if urllib.parse.urlsplit(final).netloc.replace("www.", "") != urllib.parse.urlsplit(url).netloc.replace("www.", ""):
                    return ("redirect", final)
                return ("ok", str(r.status))
        except urllib.error.HTTPError as e:
            if method == "HEAD" and e.code in (400, 403, 405, 501):
                continue
            return ("dead", f"HTTP {e.code}")
        except Exception as e:
            if method == "HEAD":
                continue
            return ("dead", type(e).__name__ + ": " + str(e)[:80])
    return ("dead", "no response")


def main():
    links = collect()
    internal = {k: v for k, v in links.items() if "://" not in k}
    external = {k: v for k, v in links.items() if "://" in k}
    broken = {k: v for k, v in internal.items() if not os.path.exists(os.path.join(PUBLIC, k))}
    with ThreadPoolExecutor(16) as ex:
        results = dict(zip(external, ex.map(probe, external)))
    site = {k: v for k, v in external.items() if any(h in k for h in SITE_HOSTS)}
    today = datetime.date.today().isoformat()

    def table(keys):
        rows = ["| link | result | on pages |", "|---|---|---|"]
        for k in sorted(keys):
            st, detail = results[k]
            pages = ", ".join(sorted(external[k]))
            rows.append(f"| `{k}` | {st}: {detail} | {pages} |")
        return "\n".join(rows)

    dead = [k for k in external if results[k][0] == "dead" and k not in site]
    redir = [k for k in external if results[k][0] == "redirect" and k not in site]
    ok = [k for k in external if results[k][0] == "ok" and k not in site]
    out = [f"# Link check ({today})", "",
           f"Generated by `just linkcheck` (`tools/linkcheck.py`) from `public/`. Counts: {len(internal)} internal, "
           f"{len(external)} external ({len(site)} to the site's own hosts).", "",
           "## Internal", "",
           "All internal links resolve to files in `public/`." if not broken else
           "\n".join(f"- `{k}` missing (on {', '.join(sorted(v))})" for k, v in sorted(broken.items())), "",
           "## Links to the site's former hosts (xwinman.org, xteddy.org, plig.net)", "", table(site), "",
           f"## External: dead ({len(dead)})", "", table(dead), "",
           f"## External: host moved ({len(redir)})", "",
           "The URL answered but landed on a different host, usually a domain-parking page or a successor site. Worth eyeballing.", "",
           table(redir), "",
           f"## External: alive ({len(ok)})", "", table(ok), ""]
    with open(os.path.join(ROOT, "docs", "links.md"), "w") as f:
        f.write("\n".join(out))
    print(f"internal broken: {len(broken)}  external dead: {len(dead)}  moved: {len(redir)}  alive: {len(ok)}  site hosts: {len(site)}")


if __name__ == "__main__":
    main()
